version: "1.0"
info:
  model: int-scaffold
packages:
- name: AutoCommitGitProject
  gitServerName: SanthoshK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.autocommitgit.integrations:a
  packages:
  - name: AutoCommitGitProject
    version: "1.0"
